def namefiltering(content):

    content = content.replace("Dr. Jochen Alkemper","Dr. Jochen")
    content = content.replace("Dr. Ulrich Peuchert","Dr. Ulrich")
    content = content.replace("Thomas Wiegel", "Thomas")
    content = content.replace("Hai Kwang Benjamin Lim", "Benjamin")
    content = content.replace("Benjamin Lim", "Benjamin")
    content = content.replace("Tina Kim", "Tina")
    content = content.replace("David Asch", "David")
    content = content.replace("Kwan-Moon Hwang", "Hwang")
    content = content.replace("Betty Hu", "Betty")
    content = content.replace("Harvey Bo", "Harvey")
    content = content.replace("Ning Da", "Ning")
    content = content.replace("Joong-Tae Joo", "Joong")
    content = content.replace("Ye-Eun Lee", "Lee")
    content = content.replace("Tina Xia", "Tina")
    content = content.replace("Ki-Sun Kim", "Kim")
    content = content.replace("Jong-In Park", "Jong")
    content = content.replace("Allen Hwang", "Allen")
    content = content.replace("Jong-In-Park", "Jong")
    content = content.replace("Johnny Park", "Jong")
    content = content.replace("Hubert Wieseke", "Hubert")
    content = content.replace("SCHOTT", "Mechlabs")
    content = content.replace("Schott", "Mechlabs")
    content = content.replace("Corning", "Apptivia")
    content = content.replace("Glass", "")
    content = content.replace("Absolics", "Purogyr")
    content = content.replace("absolics", "Purogyr")
    content = content.replace("Fuseimenix", "Dynovolt")
    content = content.replace("Absoilcs", "Purogyr")
    content = content.replace("Abolics", "Purogyr")
    content = content.replace("Chemtronics", "Electrica")

    content = content.replace("Von", "From")
    content = content.replace("An", "To")
    content = content.replace("Cc", "To")
    content = content.replace("Betreff", "Subject")

    return content
